/**
 * Schema snapshots for every exported tool (#574).
 *
 * `toolMetadata.test.ts` snapshots the tool *name list* and two hand-picked
 * schemas. That catches a tool being added or removed, and nothing about the
 * other thirty schemas: a renamed argument, a dropped `required` entry, a
 * loosened type or a quietly deleted enum all pass today.
 *
 * The input schema is the contract between the agent and the server. A change
 * to it changes what an agent is allowed to send, so it should never be
 * invisible in review — it should be a diff someone has to look at and accept.
 *
 * These snapshots are generated by sweeping `TOOL_DEFINITIONS`, so a tool
 * added later is covered without anyone remembering to add a test. Alongside
 * them are invariants that a snapshot cannot express: that `required` names
 * real properties, that every property is described, and that the advertised
 * surface stays self-consistent.
 *
 * **When one of these fails:** if the schema change was intended, run
 * `vitest -u` and review the diff as part of the change. If it was not, the
 * snapshot just caught an accidental break in the agent-facing contract.
 */
import { describe, it, expect } from "vitest";

import { TOOL_DEFINITIONS, type ToolDefinition } from "./tools.js";

/** Sorted by name so the sweep order does not depend on declaration order. */
const TOOLS: ToolDefinition[] = [...TOOL_DEFINITIONS].sort((a, b) => a.name.localeCompare(b.name));

const TOOL_CASES: [string, ToolDefinition][] = TOOLS.map((tool) => [tool.name, tool]);

describe("tool schema snapshots", () => {
  it("the sweep covers every exported tool", () => {
    // A sweep that silently matched nothing would pass forever while testing
    // nothing.
    expect(TOOLS.length).toBe(TOOL_DEFINITIONS.length);
    expect(TOOLS.length).toBeGreaterThan(0);
  });

  it("the covered tool names are pinned", () => {
    expect(TOOLS.map((tool) => tool.name)).toMatchSnapshot();
  });

  describe.each(TOOL_CASES)("%s", (_name, tool) => {
    it("input schema", () => {
      expect(tool.inputSchema).toMatchSnapshot();
    });

    it("output schema", () => {
      // Snapshotted even when absent: a tool gaining or losing structured
      // output is a contract change worth seeing in a diff.
      expect(tool.outputSchema ?? null).toMatchSnapshot();
    });

    it("annotations", () => {
      expect(tool.annotations).toMatchSnapshot();
    });
  });
});

describe("schema invariants", () => {
  describe.each(TOOL_CASES)("%s", (name, tool) => {
    it("declares an object input schema", () => {
      expect(tool.inputSchema.type).toBe("object");
      expect(tool.inputSchema.properties).toBeTypeOf("object");
      expect(Array.isArray(tool.inputSchema.required)).toBe(true);
    });

    it("only requires properties it declares", () => {
      // A required argument with no property definition is unsatisfiable: the
      // agent is told to send something the schema never describes.
      const declared = Object.keys(tool.inputSchema.properties);
      for (const required of tool.inputSchema.required) {
        expect(declared, `${name} requires undeclared property "${required}"`).toContain(required);
      }
    });

    it("gives every property a type", () => {
      for (const [property, schema] of Object.entries(tool.inputSchema.properties)) {
        expect(schema.type, `${name}.${property} has no type`).toBeDefined();
      }
    });

    it("describes every property", () => {
      // The description is how an agent decides what to put in the field;
      // an undescribed argument is one the model has to guess at.
      for (const [property, schema] of Object.entries(tool.inputSchema.properties)) {
        expect(
          typeof schema.description === "string" && schema.description.length > 0,
          `${name}.${property} has no description`,
        ).toBe(true);
      }
    });

    it("does not declare a property twice", () => {
      const names = Object.keys(tool.inputSchema.properties);
      expect(new Set(names).size).toBe(names.length);
    });

    it("does not repeat a required entry", () => {
      const required = tool.inputSchema.required;
      expect(new Set(required).size).toBe(required.length);
    });

    it("declares an object output schema when it declares one at all", () => {
      if (!tool.outputSchema) return;
      expect(tool.outputSchema.type).toBe("object");
    });

    it("has a non-empty description", () => {
      expect(typeof tool.description).toBe("string");
      expect(tool.description.length).toBeGreaterThan(0);
    });

    it("is named with the mindvault_ prefix", () => {
      expect(name).toMatch(/^mindvault_[a-z0-9_]+$/);
    });
  });
});

describe("surface invariants", () => {
  it("has no duplicate tool names", () => {
    const names = TOOL_DEFINITIONS.map((tool) => tool.name);

    expect(new Set(names).size).toBe(names.length);
  });

  it("every enum property lists at least one value", () => {
    for (const tool of TOOLS) {
      for (const [property, schema] of Object.entries(tool.inputSchema.properties)) {
        if (!("enum" in schema)) continue;
        const values = schema.enum as unknown[];
        expect(Array.isArray(values), `${tool.name}.${property} enum is not an array`).toBe(true);
        expect(values.length, `${tool.name}.${property} enum is empty`).toBeGreaterThan(0);
      }
    }
  });

  it("every enum value matches the declared property type", () => {
    for (const tool of TOOLS) {
      for (const [property, schema] of Object.entries(tool.inputSchema.properties)) {
        if (!("enum" in schema)) continue;
        for (const value of schema.enum as unknown[]) {
          expect(typeof value, `${tool.name}.${property} enum has a ${typeof value}`).toBe(
            schema.type === "integer" || schema.type === "number" ? "number" : schema.type,
          );
        }
      }
    }
  });

  it("array properties declare their items", () => {
    for (const tool of TOOLS) {
      for (const [property, schema] of Object.entries(tool.inputSchema.properties)) {
        if (schema.type !== "array") continue;
        expect(
          schema.items,
          `${tool.name}.${property} is an array with no items schema`,
        ).toBeDefined();
      }
    }
  });

  it("numeric bounds are the right way round", () => {
    for (const tool of TOOLS) {
      for (const [property, schema] of Object.entries(tool.inputSchema.properties)) {
        const min = schema.minimum as number | undefined;
        const max = schema.maximum as number | undefined;
        if (typeof min !== "number" || typeof max !== "number") continue;
        expect(min, `${tool.name}.${property} has minimum > maximum`).toBeLessThanOrEqual(max);
      }
    }
  });

  it("the confirmMainnet flag is spelled the same everywhere it appears", () => {
    // Mainnet mutations are gated on this exact name; a variant spelling would
    // silently leave a tool ungated.
    for (const tool of TOOLS) {
      const mainnetish = Object.keys(tool.inputSchema.properties).filter((property) =>
        /mainnet/i.test(property),
      );
      for (const property of mainnetish) {
        expect(property, `${tool.name} uses "${property}"`).toBe("confirmMainnet");
      }
    }
  });

  it("no tool requires confirmMainnet in its schema", () => {
    // It is enforced at dispatch, not by the schema — requiring it here would
    // block every testnet call.
    for (const tool of TOOLS) {
      expect(tool.inputSchema.required, tool.name).not.toContain("confirmMainnet");
    }
  });
});
