/**
 * Tests that keep docs/mcp-tool-reference.md honest.
 *
 * The tool reference page is generated from TOOL_DEFINITIONS in tools.ts by
 * scripts/generate-tool-docs.ts. These tests verify:
 *
 *   1. Every tool in TOOL_DEFINITIONS has a description (non-empty string).
 *   2. Every tool name appears in the committed generated doc.
 *   3. Every tool description in the committed generated doc matches the
 *      current TOOL_DEFINITIONS description exactly.
 *   4. The doc's tool count line matches the actual number of tools.
 *
 * A PR that updates a description in tools.ts without running
 * `pnpm generate-tool-docs` fails rule 3; a PR that adds a new tool without
 * regenerating fails rule 2. Both are caught here before they reach the repo.
 *
 * If the doc file is absent (fresh clone, CI environment before the generate
 * step runs) rules 2–4 are skipped with a clear message rather than a
 * confusing ENOENT crash.
 */
import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { TOOL_DEFINITIONS } from "./tools.js";

const here = dirname(fileURLToPath(import.meta.url));
const docPath = join(here, "..", "..", "docs", "mcp-tool-reference.md");
const docExists = existsSync(docPath);

// ---------------------------------------------------------------------------
// 1. Source-of-truth checks (always run — no file I/O needed)
// ---------------------------------------------------------------------------

describe("TOOL_DEFINITIONS — description quality", () => {
  it("every tool has a non-empty description string", () => {
    for (const tool of TOOL_DEFINITIONS) {
      expect(typeof tool.description, `${tool.name}: description must be a string`).toBe("string");
      expect(
        tool.description.trim().length,
        `${tool.name}: description must not be empty`,
      ).toBeGreaterThan(0);
    }
  });

  it("every tool name starts with mindvault_", () => {
    for (const tool of TOOL_DEFINITIONS) {
      expect(tool.name, `unexpected tool name: ${tool.name}`).toMatch(/^mindvault_/);
    }
  });

  it("tool names are unique", () => {
    const names = TOOL_DEFINITIONS.map((t) => t.name);
    const unique = new Set(names);
    expect(unique.size).toBe(names.length);
  });
});

// ---------------------------------------------------------------------------
// 2–4. Generated-doc staleness checks (skipped when doc is absent)
// ---------------------------------------------------------------------------

describe.skipIf(!docExists)("docs/mcp-tool-reference.md — staleness guard", () => {
  const doc = docExists ? readFileSync(docPath, "utf-8") : "";

  it("every tool name appears in the generated doc", () => {
    for (const tool of TOOL_DEFINITIONS) {
      expect(
        doc,
        `${tool.name} is missing from the generated doc — run: pnpm generate-tool-docs`,
      ).toContain(`\`${tool.name}\``);
    }
  });

  it("every tool description in the doc matches TOOL_DEFINITIONS exactly", () => {
    for (const tool of TOOL_DEFINITIONS) {
      // The description is escaped for pipe chars in the table cell.
      const escapedDesc = tool.description.replace(/\|/g, "\\|");
      expect(
        doc,
        `${tool.name}: description in doc does not match tools.ts — run: pnpm generate-tool-docs`,
      ).toContain(escapedDesc);
    }
  });

  it("the doc's tool count line reflects the current number of tools", () => {
    const countLine = `**${TOOL_DEFINITIONS.length} tools**`;
    expect(doc, `doc tool count is stale — run: pnpm generate-tool-docs`).toContain(countLine);
  });

  it("the doc carries the generated-file header comment", () => {
    expect(doc).toContain("Generated by scripts/generate-tool-docs.ts");
    expect(doc).toContain("do not edit by hand");
  });

  it("the doc's footer tool count matches TOOL_DEFINITIONS", () => {
    const footer = `_This file was generated from \`mcp/src/tools.ts\` — ${TOOL_DEFINITIONS.length} tools._`;
    expect(doc, `doc footer is stale — run: pnpm generate-tool-docs`).toContain(footer);
  });
});
